dependencies:
- name: zookeeper
  version: 0.6.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
- name: postgresql
  version: 0.9.2
  repository: https://kubernetes-charts.storage.googleapis.com
